services:
  mlflow:
    image: python:3.10-slim
    container_name: mlflow_ui
    ports:
      - "5000:5000"
    volumes:
      - "D:/WORKSPACE/OFIICE_WORKS/model/src/mlruns:/mlruns"
    working_dir: /mlruns
    command: >
      sh -c "pip install mlflow && mlflow ui --backend-store-uri file:/mlruns --host 0.0.0.0 --port 5000"
