[project]
name = "model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "language-tool-python>=2.9.5",
    "sentence-transformers>=5.1.2",
    "textblob>=0.19.0",
]

[tool.uv.workspace]
members = [
    "src",
]
